algo = input("Digite alguma coisa: ")
print("O tipo primitivo desse valor é", type(algo))
print("Só tem espaços ?", algo.isspace())
print("É um número ?", algo.isnumeric())
print("É alfabético ?", algo.isalpha())
print("É alfanumérico ?", algo.isalnum())
print("Esta em minusculas ?", algo.islower())
print("Esta em maiúsculas ?", algo.isupper())
print("Esta capitalizado ?", algo.istitle())